Reduce the dependency on Reactive Streams Operators
smallrye/smallrye-reactive-messaging pull request #1364
Opened 2021-08-19 12:38 UTC by cescoffier

WIP.

2021-09-15 16:12 UTC, ozangunalp requested changes
Overall, it looks good to me. I added a couple of minor comments

2021-09-15 16:46 UTC, cescoffier commented on smallrye-reactive-messaging-provider/src/main/java/io/smallrye/reactive/messaging/impl/ConnectorFactories.java
> +            // TODO Extract
Good point, I forgot to extract the exception to the ProviderExceptions class.

2021-09-15 16:51 UTC, cescoffier commented on smallrye-reactive-messaging-provider/src/main/java/io/smallrye/reactive/messaging/extension/ChannelProducer.java
>          String name = getChannelName(injectionPoint);
Where? 

Do you mean `return Multi.createFrom().publisher(list.get(0));`. This is required because we need a Multi.

2021-09-15 16:53 UTC, cescoffier commented on smallrye-reactive-messaging-provider/src/main/java/io/smallrye/reactive/messaging/helpers/MultiUtils.java
> +            if (configuration.getAcknowledgment() == Acknowledgment.Strategy.PRE_PROCESSING) {
Yes. That's roughly equivalent because `plug` is called only once.

2021-09-16 06:53 UTC, ozangunalp commented on smallrye-reactive-messaging-provider/src/main/java/io/smallrye/reactive/messaging/extension/ChannelProducer.java
>          String name = getChannelName(injectionPoint);
I was talking about the two `Multi.createFrom().publisher` calls inside this method https://github.com/cescoffier/smallrye-reactive-messaging/blob/9d35b79457c19e2d8a8cc63981595c3d18f528fb/smallrye-reactive-messaging-provider/src/main/java/io/smallrye/reactive/messaging/extension/ChannelProducer.java#L52

2021-09-16 07:43 UTC, cescoffier commented on smallrye-reactive-messaging-provider/src/main/java/io/smallrye/reactive/messaging/extension/ChannelProducer.java
>          String name = getChannelName(injectionPoint);
You're right! It's not required anymore.
Note that the `createFrom().publisher()` return immediately if the passed publisher is a `Multi`. But that's an additional useless call.

2021-09-16 08:10 UTC, ozangunalp commented on smallrye-reactive-messaging-provider/src/main/java/io/smallrye/reactive/messaging/extension/ChannelProducer.java
>          String name = getChannelName(injectionPoint);
I checked if it returns immediately in case of `Multi` but it doesn't. There is still an `AbstractMulti` created with delegation of the subscriber

2021-09-16 08:13 UTC, cescoffier commented on smallrye-reactive-messaging-provider/src/main/java/io/smallrye/reactive/messaging/extension/ChannelProducer.java
>          String name = getChannelName(injectionPoint);
Hum... I need to check why we do this. Maybe @jponge has an idea? I was pretty sure I had a fast branch.

2021-09-16 08:40 UTC, jponge commented on smallrye-reactive-messaging-provider/src/main/java/io/smallrye/reactive/messaging/extension/ChannelProducer.java
>          String name = getChannelName(injectionPoint);
You might use `safePublisher` which assumes a well-behaving `Publisher`, while `publisher` stays on the safe side with badly implemented ones.

2021-09-16 11:42 UTC, cescoffier commented on smallrye-reactive-messaging-provider/src/main/java/io/smallrye/reactive/messaging/extension/ChannelProducer.java
>          String name = getChannelName(injectionPoint);
ah ah, that's why :-) 
As I implemented the other Multi, I would qualify it as "safe" :-D 

Anyway, the rewrapping was unnecessary in this case.

2021-09-17 05:50 UTC, cescoffier commented on smallrye-reactive-messaging-provider/src/main/java/io/smallrye/reactive/messaging/impl/ConnectorFactories.java
> +                // TODO Extract
Fixed.

2021-09-27 12:24 UTC, cescoffier commented
@ozangunalp I cleaned up the ChannelProducer class to remove the useless `Multi.createFrom().publisher`

2021-09-27 12:34 UTC, ozangunalp approved these changes

2021-09-27 13:11 UTC, merged