Handle Vert.x Contex tin MutinyEmitter.send
smallrye/smallrye-reactive-messaging pull request #1434
Opened 2021-09-27 16:43 UTC by cescoffier

When the `MutinyEmitter.send` method is called from a Vert.x context, the acknowledgement event should be emitted on the same context.

This PR captures the context in the `send` method, if there is one.
In this case, it emits the result on the same context.

2021-09-27 16:44 UTC, cescoffier commented
CC @unfromage

2021-09-27 16:57 UTC, Emily-Jiang reviewed
@cescoffier Does this mean the core SmallRye Reactive Messaging require Vert.x?

2021-09-27 17:05 UTC, cescoffier commented
@Emily-Jiang Not as mandatory, but some features use Vert.x. If you use the regular Emitter, Vert.x is not required. If you use the MutinyEmitter, then yes. Suppose you are interested in using the MutinyEmitter without Vert.x, you can propose a PR checking if Vert.x is available. 

BTW, last time I checked, Open Liberty was using an older version of SmallRye Reactive Messaging. This PR only targets the 3.x (main) branch. 2.x is not changed.

2021-09-27 21:42 UTC, Emily-Jiang commented
> @Emily-Jiang Not as mandatory, but some features use Vert.x. If you use the regular Emitter, Vert.x is not required. If you use the MutinyEmitter, then yes. Suppose you are interested in using the MutinyEmitter without Vert.x, you can propose a PR checking if Vert.x is available.
> 
Thank you @cescoffier ! If Vert.x is not avaiable, will MutinyEitter work at all? MutinyEmitter is in the core though. If I consume the core module, without Vert.x, the module will not function. Right?
> BTW, last time I checked, Open Liberty was using an older version of SmallRye Reactive Messaging. This PR only targets the 3.x (main) branch. 2.x is not changed.
Yes, you were right. However, Open Liberty plans to consume the latest SmallRye Reactive Messaging. Therefore, I am cautious on introducing mandatory dependencies on Vert.x in the core again.

2021-09-28 05:36 UTC, cescoffier commented
@Emily-Jiang You can still use the module without Vert.x. As I said some features won't work, but they are not part of the spec (so you can pass the TCK without Vert.x being present). This PR does not change this, there are other dependencies. If that's a concern for your integration, PRs are welcome.

2021-09-28 08:29 UTC, ozangunalp requested changes
The change itself seems ok to me. Although `AbstractEmitter` is still a head-scratcher.

2021-09-28 08:29 UTC, ozangunalp commented on smallrye-reactive-messaging-provider/src/test/java/io/smallrye/reactive/messaging/inject/MutinyEmitterInjectionTest.java
> +        unis.get(1).invoke(x -> reference.set(Vertx.currentContext())).await().indefinitely();
Isn't there a second assert missing ?

2021-09-28 11:21 UTC, cescoffier commented on smallrye-reactive-messaging-provider/src/test/java/io/smallrye/reactive/messaging/inject/MutinyEmitterInjectionTest.java
> +        unis.get(1).invoke(x -> reference.set(Vertx.currentContext())).await().indefinitely();
Yes, fixed.

2021-09-28 12:13 UTC, ozangunalp approved these changes

2021-09-28 12:59 UTC, merged