Implement Cloud Event support for the AMQP connector
smallrye/smallrye-reactive-messaging pull request #1517
Opened 2021-11-17 17:25 UTC by cescoffier

This PR adds support for Cloud Event for the AMQP connector.
It follows the AMQP Protocol Binding specification (https://github.com/cloudevents/spec/blob/v1.0.1/amqp-protocol-binding.md) and supports both the binary and structured more for incoming and outgoing messages.

The configuration is similar to the Kafka one.

Related to https://github.com/quarkusio/quarkus/issues/21435.

2021-11-17 18:04 UTC, ozangunalp requested changes
All good except the backtick in the connector attribute description

2021-11-17 18:05 UTC, cescoffier commented on smallrye-reactive-messaging-amqp/src/main/java/io/smallrye/reactive/messaging/amqp/AmqpConnector.java
> +@ConnectorAttribute(name = "cloud-events-insert-timestamp", type = "boolean", direction = ConnectorAttribute.Direction.OUTGOING, description = "Whether or not the connector should insert automaticall
ah ah, I think we need to fix that one twice (because it's a copy from Kafka)

2021-11-17 18:05 UTC, cescoffier commented
I believe the CI failure was related... let's see.

2021-11-17 18:08 UTC, cescoffier commented on smallrye-reactive-messaging-amqp/src/main/java/io/smallrye/reactive/messaging/amqp/AmqpConnector.java
> +@ConnectorAttribute(name = "cloud-events-insert-timestamp", type = "boolean", direction = ConnectorAttribute.Direction.OUTGOING, description = "Whether or not the connector should insert automaticall
Fixed - twice.

2021-11-19 19:42 UTC, ozangunalp approved these changes

2021-11-21 16:11 UTC, merged