Make camel test more robust
smallrye/smallrye-reactive-messaging pull request #1527
Opened 2021-11-23 08:23 UTC by OpenGuidou

I've aligned the camel timeout to the one defined for nats, and adding a retry mechanism on the test.

Could you run the CI a few times and check if it improves the situation ?

2021-11-23 13:03 UTC, cescoffier requested changes

2021-11-23 13:03 UTC, cescoffier commented on smallrye-reactive-messaging-camel/src/test/java/io/smallrye/reactive/messaging/camel/outgoing/OutgoingCamelTest.java
>                      .supplyAsync(
I would not use supplyAsync with a specific executor. The behavior is not the one you think when the level of parallelism is 1.

2021-11-23 13:03 UTC, cescoffier commented on smallrye-reactive-messaging-camel/src/test/java/io/smallrye/reactive/messaging/camel/outgoing/OutgoingCamelTest.java
> +                                    .receive("nats:out?servers=127.0.0.1:7656&connectionTimeout=60000", 60000));
I don't believe it's a timeout issue, but let's see.

2021-11-23 13:04 UTC, cescoffier commented
I'm going to execute the CI build a few times to be sure it fixes the issue.

2021-11-25 06:50 UTC, cescoffier approved these changes

2021-11-25 06:50 UTC, merged

2021-11-25 12:57 UTC, OpenGuidou commented
Should I understand that it was better that before ?

2021-11-25 13:03 UTC, cescoffier commented
I ran the CI a few times and it seems to be fine. Let's see how it is going to behave in the next few days.