Fix kafka broker extension
smallrye/smallrye-reactive-messaging pull request #1621
Opened 2022-02-17 09:46 UTC by ozangunalp

- Fix for junit extension for Kafka broker, which creates a single broker for all the test suite
- KafkaCompanion producer and consumer creation accept untyped Serde classes for configuring generic Serde ex. avro

2022-02-17 10:01 UTC, cescoffier requested changes

2022-02-17 10:27 UTC, ozangunalp commented on smallrye-reactive-messaging-kafka-test-companion/src/main/java/io/smallrye/reactive/messaging/kafka/companion/ConsumerBuilder.java
> +            Class<? extends Deserializer> keyDeserType, Class<? extends Deserializer> valueDeserType) {
I was aiming for type erasure but yes `Class<? extends Deserializer<?>>` would work perfectly.

2022-02-17 10:52 UTC, ozangunalp commented on smallrye-reactive-messaging-kafka-test-companion/src/main/java/io/smallrye/reactive/messaging/kafka/companion/test/KafkaBrokerExtension.java
> +        KafkaBrokerExtension extension = (KafkaBrokerExtension) globalStore.get(KafkaBrokerExtension.class);
It is used like any other key on the global store here. The fix is to stop using static fields on the `KafkaBrokerExtension` class for having a single broker instance for a test suite.

It was difficult to reproduce local but I assume the original issue was that when a surefire fork is reused it _can_ execute a different test suite that uses the same extension, with its static fields.

2022-02-17 10:59 UTC, ozangunalp commented
@cescoffier I am starting to think that it is still too early to use kraft mode in tests

2022-02-18 11:26 UTC, ozangunalp commented
This along with https://github.com/strimzi/test-container/pull/31 will help to stabilise the tests.

2022-02-18 12:29 UTC, cescoffier approved these changes

2022-02-20 18:06 UTC, merged