Use the Mutiny Zero RS TCK JUnit5 shim
smallrye/smallrye-reactive-messaging pull request #1823
Opened 2022-07-25 16:53 UTC by jponge

2022-07-25 16:55 UTC, jponge commented
Hum not sure what had already been merged before, but this brings up to the latest version 😉

2022-07-26 06:53 UTC, cescoffier requested changes
Is it just a bump of the TCK? 

I'm more worried about the import and format changes.

2022-07-26 06:53 UTC, cescoffier commented on smallrye-reactive-messaging-kafka/src/test/java/io/smallrye/reactive/messaging/kafka/ce/KafkaSourceBatchWithCloudEventsTest.java
> +import io.smallrye.reactive.messaging.kafka.base.BufferSerde;
@ozangunalp yet another import ordering issue?

2022-07-26 06:53 UTC, cescoffier commented on smallrye-reactive-messaging-kafka/src/test/java/io/smallrye/reactive/messaging/kafka/ce/KafkaSourceWithCloudEventsTest.java
> +                new JsonObjectSerde.JsonObjectDeserializer()));
Looks like we also have a formatter issue.

2022-07-26 07:16 UTC, jponge commented
So:

1. it's a Mutiny Zero bump,
2. formatting is what I got locally after a proper Maven build, I guess it's what should be under VCS

2022-07-26 09:30 UTC, jponge commented
Yes but there's a version bump.

2022-07-26 09:30 UTC, ozangunalp commented
When I rebase the branch onto `upstream/main` I get "dropping 2fdd947915bc48d6f39b8b1bfbf6fd14f31d37c1 Use Mutiny Zero 0.4.2 -- patch contents already upstream"

2022-07-26 09:31 UTC, jponge commented
Ok stupid me then, I had already opened that PR before 🤣

2022-07-26 09:31 UTC, closed without merging

2022-07-26 09:34 UTC, ozangunalp commented
Back to the future