Decorate emitters with PublisherDecorators
smallrye/smallrye-reactive-messaging pull request #2342
Opened 2023-10-23 16:29 UTC by ozangunalp

Resolves #2332 
May supersede #2336

2023-10-24 06:10 UTC, cescoffier requested changes

2023-10-24 06:10 UTC, cescoffier commented on smallrye-reactive-messaging-provider/src/main/java/io/smallrye/reactive/messaging/providers/wiring/Wiring.java
> +                // TODO do not apply ContextDecorator here, it messes with custom emitter transactions
Any reason why?

2023-10-24 06:10 UTC, cescoffier commented on smallrye-reactive-messaging-provider/src/main/java/io/smallrye/reactive/messaging/providers/wiring/Wiring.java
> +                // TODO do not apply ContextDecorator here, it messes with custom emitter transactions
If we do not apply it, how to we associate the context to the message?

2023-10-24 06:10 UTC, cescoffier commented on smallrye-reactive-messaging-provider/src/main/java/io/smallrye/reactive/messaging/providers/wiring/Wiring.java
> +                    publisher = decorator.decorate(publisher, configuration.name(), false);
So, you consider the emitter as a "not connector", which is exact. However, I was wondering if we need to be specific in this case and introduce a second flag (I'm not a big fan of signatures containing two exclusive flags, having an enum would be better).

However, do we need to know when it's an emitter?

2023-10-25 18:01 UTC, ozangunalp commented
@cescoffier pushed a fix for Kafka transactions. It appears that applying ContextDecorator there changes the tx flow order, flushing and commiting the Tx before records are sent. Now it captures sent record Uni's and makes sure that all of them are sent before flusing and committing.

2023-11-02 13:14 UTC, ozangunalp commented
@cescoffier shall we get this in ?

2023-11-02 13:15 UTC, cescoffier commented
Yes!

2023-11-02 13:19 UTC, merged