Pulsar force schema fetch on pulsar-client-thread for all schema requiring schema info fetching
smallrye/smallrye-reactive-messaging pull request #2494
Opened 2024-02-21 16:57 UTC by ozangunalp

Fixes #2493

2024-02-21 17:34 UTC, cescoffier submitted a review, later dismissed

2024-02-22 07:14 UTC, marekczajkowski commented on smallrye-reactive-messaging-pulsar/src/main/java/io/smallrye/reactive/messaging/pulsar/PulsarIncomingChannel.java
> +                        if (schema.requireFetchingSchemaInfo()) {
The same mechanism should be used for batch see line 141

2024-02-22 07:17 UTC, marekczajkowski requested changes
Add same mechanism for batch case

2024-02-22 07:24 UTC, ozangunalp commented
@marekczajkowski thanks for pointing it out. I pushed the fix.

2024-02-22 15:53 UTC, merged