Document dynamic topic names
smallrye/smallrye-reactive-messaging pull request #787
Opened 2020-10-02 14:37 UTC by loicmathieu

Fixes #780

2020-10-02 14:37 UTC, loicmathieu commented
/cc @kenfinnigan 
To avoid duplication between example maybe I should remove the override of the topic name from the previous example ?

2020-10-02 14:41 UTC, kenfinnigan commented
Probably not a bad idea @loicmathieu 

What do you think @cescoffier?

2020-10-02 17:10 UTC, cescoffier requested changes

2020-10-02 17:10 UTC, cescoffier commented on documentation/src/main/doc/modules/amqp/pages/outbound.adoc
> +Sometimes it is desirable to dynamically select the destination of a message, in this case you should not configure the name of the topic inside your application configuration file,
```suggestion
Sometimes it is desirable to select the destination of a message dynamically.
In this case, you should not configure the address inside your application configuration file, but instead, use the outbound metadata to set the address.```

2020-10-02 17:10 UTC, cescoffier commented on documentation/src/main/doc/modules/amqp/pages/outbound.adoc
> +but instead use the outbound metadata to set the name of the topic.
To be removed, part of my suggestion above.

2020-10-02 17:10 UTC, cescoffier commented on documentation/src/main/doc/modules/amqp/pages/outbound.adoc
> +For example, you can route to a dynamic topic based on the incoming message:
```suggestion
For example, you can send to a dynamic address based on the incoming message:
```

2020-10-02 17:10 UTC, cescoffier commented on documentation/src/main/doc/modules/amqp/examples/outbound/AmqpOutboundDynamicTopicExample.java
> +            .withAddress(topicName)
don't use `topic` for AMQP. Use address instead.

2020-10-02 17:10 UTC, cescoffier commented on documentation/src/main/doc/modules/kafka/pages/outbound.adoc
> +Sometimes it is desirable to dynamically select the destination of a message, in this case you should not configure the name of the topic inside your application configuration file,
```suggestion
Sometimes it is desirable to select the destination of a message dynamically. In this case, you should not configure the topic inside your application configuration file, but instead, use the outbound metadata to set the name of the topic.```

2020-10-02 17:10 UTC, cescoffier commented on documentation/src/main/doc/modules/kafka/pages/outbound.adoc
> +but instead use the outbound metadata to set the name of the topic.
to be removed, part of my suggestion above.

2020-10-02 17:10 UTC, cescoffier commented on documentation/src/main/doc/modules/kafka/pages/outbound.adoc
> +NOTE: To be able to set the address per message, the connector is using an _anonymous sender_.
Hum... there is no such a thing in the Kafka world :-) ... yet

2020-10-05 07:24 UTC, loicmathieu commented
@cescoffier I suggestions applied!

Do you think I should remove the override of the topic/address name from the previous example  to avoid duplication ?

2020-10-05 08:25 UTC, cescoffier commented
@loicmathieu Oh damned! I missed that. Yes, would be better to avoid the overlap.

2020-10-05 08:42 UTC, loicmathieu commented
@cescoffier @kenfinnigan I remove the topic/address override from the previous section. Good to go ?

2020-10-05 08:44 UTC, cescoffier approved these changes

2020-10-05 08:44 UTC, cescoffier commented
All good for me! Thanks @loicmathieu !

2020-10-05 13:05 UTC, kenfinnigan approved these changes
Thanks @loicmathieu

2020-10-05 13:05 UTC, merged